// Downloads openly-licensed Kashi / yatra photography from Wikimedia Commons
// into public/images/ and writes data/image-credits.js with attribution.
import fs from "node:fs";
import path from "node:path";
import https from "node:https";

const ROOT = "/Users/nikhil/Downloads/priority clients/nimmagadda vari";
const OUT = path.join(ROOT, "public/images");
fs.mkdirSync(OUT, { recursive: true });

const WANTED = [
  ["kashi-temple", "File:Shri Kashi Vishwanath Temple 2.jpg"],
  ["ganga-sunrise", "File:Boats at sunrise Ganges River Varanasi Uttar Pradesh Schwiki.jpg"],
  ["ganga-aarti", "File:Ganga Aarti at Varanasi in the evening.jpg"],
  ["kashi-vishwanath", "File:Shri Kashi Vishwanath Temple 3.jpg"],
  ["dashashwamedh-ghat", "File:Dashashwamedh Ghat Varanasi.jpg"],
  ["assi-ghat", "File:Assi ghat banaras mandiro ka seher.jpg"],
  ["ghats-pilgrims", "File:People Varanasi Ghats 2.jpg"],
  ["ganges-evening", "File:Varanasi, India, Ganges River after sunset.jpg"],
  ["boat-ride", "File:Boat ride at Sunrise, on the Ganges, Varanasi.jpg"],
  ["sarnath", "File:Dhamek Stupa, 2025.jpg"],
  ["prayagraj", "File:Prayagraj Sangam 2.jpg"],
  ["ayodhya", "File:Shri Ram Janambhoomi Mandir, Ayodhya Dham.jpg"],
  ["mathura", "File:Mathura Temple-Mathura-India0001.JPG"],
  ["agra", "File:Taj Mahal, Agra, India edit2.jpg"],
  ["gaya", "File:Vishnupad temple gaya bihar.jpg"],
  ["andhra-meals", "File:South Indian thali-Saravana bhawan-New Delhi-6.jpg"],
  // Fleet: stock photos of the vehicle type, not the trust's own vehicles.
  ["fleet-car", "File:Toyota Innova Crysta 2.4 Z side.jpg"],
  ["fleet-traveller", "File:Force Motors - Traveller 26 - Agra 2014-05-14 4222.JPG"],
  ["fleet-bus", "File:Scania Metrolink HD 14.5 M Ashwamedh.jpg"],
];

const UA = { "User-Agent": "nimmagadda-vari-trust-site/1.0 (build script)" };

function fetchText(url) {
  return new Promise((res, rej) => {
    https.get(url, { headers: UA }, (r) => {
      let d = "";
      r.on("data", (c) => (d += c));
      r.on("end", () => res(d));
    }).on("error", rej);
  });
}

function download(url, dest) {
  return new Promise((res, rej) => {
    https.get(url, { headers: UA }, (r) => {
      if (r.statusCode >= 300 && r.statusCode < 400 && r.headers.location) {
        return download(r.headers.location, dest).then(res, rej);
      }
      if (r.statusCode !== 200) return rej(new Error("HTTP " + r.statusCode));
      const f = fs.createWriteStream(dest);
      r.pipe(f);
      f.on("finish", () => f.close(() => res(fs.statSync(dest).size)));
    }).on("error", rej);
  });
}

const strip = (html) =>
  String(html || "")
    .replace(/<[^>]*>/g, "")
    .replace(/\s+/g, " ")
    .trim();

const credits = [];

for (const [slug, title] of WANTED) {
  const api =
    "https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=imageinfo" +
    "&iiprop=url|extmetadata&iiurlwidth=2000&titles=" +
    encodeURIComponent(title);
  try {
    const j = JSON.parse(await fetchText(api));
    const page = Object.values(j.query.pages)[0];
    const ii = page?.imageinfo?.[0];
    if (!ii) {
      console.log("MISS", slug, title);
      continue;
    }
    const meta = ii.extmetadata || {};
    const url = (ii.thumburl || ii.url).split("?")[0];
    const file = path.join(OUT, `${slug}.jpg`);
    const bytes = await download(url, file);
    credits.push({
      slug,
      file: `/images/${slug}.jpg`,
      title: strip(meta.ObjectName?.value) || title.replace(/^File:/, ""),
      author: strip(meta.Artist?.value) || "Unknown",
      license: strip(meta.LicenseShortName?.value) || "See source",
      licenseUrl: meta.LicenseUrl?.value || "",
      source: ii.descriptionurl || "",
    });
    console.log("OK  ", slug, (bytes / 1024).toFixed(0) + "KB");
  } catch (e) {
    console.log("FAIL", slug, e.message);
  }
}

fs.writeFileSync(
  path.join(ROOT, "data/image-credits.js"),
  `// Photography sourced from Wikimedia Commons. Generated by scripts/fetch-images.mjs.
// Several licences (CC BY, CC BY-SA, GODL-India) require visible attribution,
// which is why /credits exists and is linked from the footer.
export const imageCredits = ${JSON.stringify(credits, null, 2)};
`
);

console.log("\nWrote data/image-credits.js with", credits.length, "entries");
